- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest
  when: (update | default(true)) | bool # Default to true if not defined
  tags:
    - git
    - cli

- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
  when: (configure | default(true)) | bool  # Default to true if not defined
  tags:
    - git
    - cli
